---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for S3 bucket

Resources:
  AcademiaS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: academia-backend
